# Generated by Django 5.1.7 on 2025-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='cantidad_biblias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
