# Generated by Django 5.1.7 on 2025-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado')], default='ausente', max_length=10),
        ),
    ]
